add comments
Fierce-Eagle/JmeterCloud pull request #10
Opened 2021-08-24 16:54 UTC by Fierce-Eagle

2021-08-24 17:53 UTC, eof404 requested changes

2021-08-24 17:53 UTC, eof404 commented on pom.xml
> +		<dependency>
В рамках задачи зависимость не нужна

2021-08-24 17:53 UTC, eof404 commented on src/main/java/com/jmeterPractice/practice/Controllers/MainController.java
> +    public String toDo(Model model) throws Exception {
Разве здесь может быть checked exception? 
http://www.quizful.net/post/java-exceptions 

Нужно удалить throws Exception.

2021-08-24 17:53 UTC, eof404 commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
> -        Summariser summer = new Summariser("summary");
Почему удалил?

2021-08-24 17:53 UTC, eof404 commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
> +        httpSampler.setAutoRedirects(true); // поступление потоков (можно выбрать follow или auto)
Что означает "поступление потоков"?

2021-08-24 17:53 UTC, eof404 commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
>      {
codestyle - обычно открывающая скобка на той же строке, что и объявление метода

2021-08-26 03:36 UTC, Fierce-Eagle commented on pom.xml
> +		<dependency>
Исправлено

2021-08-26 03:37 UTC, Fierce-Eagle commented on src/main/java/com/jmeterPractice/practice/Controllers/MainController.java
> +    public String toDo(Model model) throws Exception {
Удалено

2021-08-26 03:39 UTC, Fierce-Eagle commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
> -        Summariser summer = new Summariser("summary");
Эта строчка, как весь блок, связанный с этим классом, был частью эксперимента по выводу информации на экран. Эксперимент был неудачным.

2021-08-26 03:42 UTC, Fierce-Eagle commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
> +        httpSampler.setAutoRedirects(true); // поступление потоков (можно выбрать follow или auto)
функции setAutoRedirects и setFollowRedirects позволяет jmeter дополнительно отследить время загрузки страницы (отслеживает поступление потоков)
        follow - будет отслеживать, но увеличится общее время отклика
        auto - не будет отслеживать, общее время отклика будет меньше

2021-08-26 03:42 UTC, Fierce-Eagle commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
>      {
Исправлено

2021-08-26 03:43 UTC, Fierce-Eagle commented on src/main/java/com/jmeterPractice/practice/HelpClasses/JmeterTesting.java
>      {
И с методом stop() тоже

2021-08-26 07:34 UTC, eof404 approved these changes

2021-08-26 07:34 UTC, MrsDramaqueen approved these changes

2021-08-26 07:35 UTC, merged